name: CI Docker Compose Actions Workflow
on: push
jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up --build -d
##########################################
jobs:
 Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          sudo apt-get update; sudo apt-get install -y curl
      ##############################################
jobs:
 Push:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl
        run: |
          curl http://localhost:3000
#################################################

  #    - name: change image name 
   #     run: docker tag my-image-name:latest lordagam/github-repo-hello-world-war5:latest
   #   - name: Login to Docker Hub
   #     uses: docker/login-action@v2
    #    with:
   #         username: ${{ secrets.DOCKERHUB_USERNAME }}
   #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 #     - name: docker push
  #      run: docker push lordagam/project_jo_tomer:frontend
        #run: docker push lordagam/project_jo_tomer:backend
        #run: docker push lordagam/project_jo_tomer:mariadb
