name: CI Docker Compose Actions Workflow
on: push
jobs:
 Build-Test-Push:
    runs-on: ubuntu-latest
    needs: Build the stack   
      - name: test
        run: |
          sudo apt-get update; sudo apt-get install -y curl

      - name: Run curl
        run: |
          curl http://localhost:3000
   
   
  #    - name: change image name 
   #     run: docker tag my-image-name:latest lordagam/github-repo-hello-world-war5:latest
   #   - name: Login to Docker Hub
   #     uses: docker/login-action@v2
    #    with:
   #         username: ${{ secrets.DOCKERHUB_USERNAME }}
   #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 #     - name: docker push
  #      run: docker push lordagam/project_jo_tomer:frontend
        #run: docker push lordagam/project_jo_tomer:backend
        #run: docker push lordagam/project_jo_tomer:mariadb
